### ISSUE TITLE
pretty print views

### ISSUE THREAD

**Issue by rrva** [omniti-labs/pg_extractor#28]
Views are dumped by pg_dump as one long line, impossible to read. 

See discussion here (patch in discussion never seemed to make it to postgresql tree):

http://thread.gmane.org/gmane.comp.db.postgresql.devel.general/198523

Can pg_extract pretty-print?

**Comment by keithf4** [comment]
I'd honestly rather not have any non-standard third-party library dependencies in pg_extractor right now. If you, or anyone else wants to write up a push request for this, I'd gladly review it and see how it looks. I don't have any plans on implementing this myself anytime soon, though.
