### ISSUE TITLE
orreplace flag doesn't actually work

### ISSUE THREAD

**Issue by plockaby** [omniti-labs/pg_extractor#34]
When I run the new python pg_extractor.py on my database with the "--orreplace" option it doesn't actually try to add "OR REPLACE" to anything. I'm using this as my command:

    pg_extractor --host xxxx --port 5432 --username postgres --dbname foo --getall --orreplace --schemadir --delete --basedir sql --nodbnamedir

When I put some debugging into the `or_replace` method I see only that it is looking in `sql/functions` but I have directories for each schema and it does not look in those.

**Comment by keithf4** [comment]
My docs actually say this only works on FUNCTIONS & VIEWS. Where else are you expecting this to be?

**Comment by keithf4** [comment]
Oh sorry, I missed that you said you have stuff in separate schema directories. I'll see if I can fix that.

**Comment by keithf4** [comment]
Fixed this in 2.3.1 (as well as another bug I encountered). Thanks for reporting the issue!

**Comment by plockaby** [comment]
Thanks for fixing it so quick! It works now.
