### ISSUE TITLE
Feature Request: Foreign Servers + User Mappings

### ISSUE THREAD

**Issue by jmealo** [omniti-labs/pg_extractor#42]
Kudos on the great work.

I was wondering if there is a way to dump foreign servers and user mappings as well?

I realize the security implications of credentials ending up in version control and that might be reason enough not to include the functionality.

Thanks,
Jeff

**Comment by keithf4** [comment]
Security implications are no different than dumping out normal roles. Can always make this an optional feature. Will give it a look when I have some time or feel free to look into adding yourself as a push request.

**Comment by keithf4** [comment]
This has been added in version 2.4.0

https://github.com/keithf4/pg_extractor/releases/tag/v2.4.0

**Comment by jmealo** [comment]
@keithf4: Thanks for implementing this.
