### ISSUE TITLE
PGPORT is ignored

### ISSUE THREAD

**Issue by gajus** [omniti-labs/pg_extractor#47]
```
PGHOST=xxx.aivencloud.com
PGPORT=23893
PGUSER=avnadmin
PGPASSWORD=xxx
```

Gives error:

```
./src/bin/pg_extractor.py --getall
Creating temp dump file...
Error in pg_dump command while creating template dump file: pg_dump: error: connection to database "avnadmin" failed: could not connect to server: Operation timed out
	Is the server running on host "xxx.aivencloud.com" (xxx) and accepting
	TCP/IP connections on port 5432?
Subprocess command called: ['pg_dump', '--format=custom', '--file=/var/folders/j0/ljpkc6ps1kb6x0ts9fmzmx3h0000gn/T/pg_extractork1des0sh', '--schema-only']

```

The key here is that it says that "TCP/IP connections on port 5432?" despite `PGPORT` configured to `23893`.

**Comment by gajus** [comment]
Using `psql` in the same prompt connects correctly.

**Comment by gajus** [comment]
Using `./src/bin/pg_extractor.py --debug` I can confirm that `PGPORT=23893` is not picked up.

**Comment by gajus** [comment]
It seems like the reason for this is that the documentation says that you can provide `PGPORT` instead of `PORT`, but `port` has a default value.

https://github.com/omniti-labs/pg_extractor/blob/master/pg_extractor.py#L1177

**Comment by keithf4** [comment]
I believe I fixed this by just removing the default in the argument options. Please let me know if it works

https://github.com/keithf4/pg_extractor/releases/tag/v2.4.0
