### ISSUE TITLE
Add PROCEDURE object type

### ISSUE THREAD

**Issue by denishpatel** [omniti-labs/pg_extractor#52]
@keithf4  Would you please add procedure type?

**Comment by keithf4** [comment]
@denishpatel Apologies for the delay on this. Initial attempt at supporting this is in PR #54 if you wouldn't mind testing it out. Mostly looking to see if overloaded procedure support works as expected.

**Comment by keithf4** [comment]
@denishpatel have you had a chance to review the PR at all?

**Comment by xvaara** [comment]
@keithf4 worked for me. Just what I needed, thanks!

**Comment by denishpatel** [comment]
@keithf4  sorry, i haven't got chance to test but thanks for adding the functionality. @xvaara thanks for testing. 

@sshellmann You might want to pull this change to extract stored procedures out of postgres using ddl script.

**Comment by keithf4** [comment]
I have merged in the PR to add procedure support
